
#ifndef STN_HFT_CONSTANTS_H
#define STN_HFT_CONSTANTS_H


#define STN_HFT_MAX_MKT_DATA_MESSAGE_TYPES				0x80	// entire ASCII table

#define STN_HFT_SOCKET_SELECT_WAIT_TIME_USEC			1

#define STB_HFT_CHNL_HP_BUFFER_SIZE_MAX				(64*1024*1024)	// 64 MB buffer size
#define STN_HFT_CHNL_MSG_SIZE_MAX					(1520+8)		// structure
#define STN_HFT_CHNL_HP_BUFFER_CNT_MAX				(STB_HFT_CHNL_HP_BUFFER_SIZE_MAX/STN_HFT_CHNL_MSG_SIZE_MAX)



#endif